### PR TITLE
Virtuoso Processing

### PR DESCRIPTION
**Pull request by mroglan**
Created pipelines for processing LIDAR and Camera data.

### CODE REVIEW

**Comment by ragingonyx** [comment]
Great work! Everything in here looks good however there are a few QOL changes I'd like to have done before merging in. 

First, in the setup.py I think we can fix it to get all the launch files automatically. The problem before was that we were missing a few imports, namely os and glob.

Additionally I don't think some of the python exec depends in the package.xml are setup properly. Check [this](http://docs.ros.org/en/jade/api/catkin/html/howto/format2/python_module_dependencies.html) out. 

We should also be adding stvl as a exec_depend, the package name for that is `spatio_temporal_voxel_layer`.

**Comment by mroglan** [comment]
Also I just realized, do I need to have an exec dependency for autoware auto?

**Comment by ragingonyx** [comment]
It's not completely necessary but it wouldn't hurt us to have that. I think we should also have our vcs repos file created for this PR too, with STVL and autoware being the main dependencies. Take a look [here](https://github.com/dirk-thomas/vcstool) for more information. I think it should be added on the same level as the packages, maybe even a folder called tools or utils.

**Comment by ragingonyx** [comment]
Documentation looks good, the only thing I would change is to make it more apparent what the ground filter is doing by providing a before image. I'll go ahead and approve this for now, but I still want the documentation to be updated when you get a chance.

**Pull request merged**
